name: Frontend CI

on:
    - pull_request

jobs:

    jest:
        name: Jest tests
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v1

            - name: Set up Node 14
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install package.json dependencies with Yarn
              run: yarn

            - name: Test with Jest
              run: yarn -v
